# Generated by Django 3.1.5 on 2021-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210203_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, upload_to='actual_images/'),
        ),
        migrations.AddField(
            model_name='actual',
            name='name',
            field=models.CharField(default='name', max_length=250, unique=True),
        ),
    ]
