# Generated by Django 3.1.5 on 2021-02-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210203_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, upload_to='actual_images'),
        ),
    ]
