# Generated by Django 3.1.5 on 2021-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210203_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, upload_to='../static/media/actual_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
