# Generated by Django 3.1.5 on 2021-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210203_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, upload_to='../media/actual_images'),
        ),
    ]
