# Generated by Django 3.1.5 on 2021-02-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210204_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPageParagraph',
            new_name='Paragraph',
        ),
    ]
