# Generated by Django 3.1.5 on 2021-02-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('living_address', models.CharField(max_length=500)),
                ('living_index', models.IntegerField(max_length=6)),
                ('registration_address', models.CharField(max_length=500)),
                ('registration_index', models.IntegerField(max_length=6)),
                ('passport_organization', models.CharField(max_length=500)),
                ('passport_date', models.DateField()),
                ('passport_series', models.IntegerField(max_length=4)),
                ('passport_number', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, upload_to='actual_images'),
        ),
    ]
