# Generated by Django 3.1.5 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210209_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(default='')),
                ('living_address', models.CharField(max_length=500)),
                ('living_index', models.IntegerField()),
                ('registration_address', models.CharField(max_length=500)),
                ('registration_index', models.IntegerField()),
                ('passport_organization', models.CharField(max_length=500)),
                ('passport_date', models.DateField(default='')),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
