# Generated by Django 3.1.5 on 2021-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210210_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforform',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
