# Generated by Django 3.1.5 on 2021-02-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_userforform_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForForm',
            new_name='UserModelForm',
        ),
    ]
