# Generated by Django 3.1.5 on 2021-02-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210211_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModelForm',
        ),
    ]
