# Generated by Django 3.1.5 on 2021-02-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210218_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual',
            options={'ordering': ('name',), 'verbose_name': 'Актуальное', 'verbose_name_plural': 'Актуальные новости'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ('text',), 'verbose_name': 'Текст на главной', 'verbose_name_plural': 'Текст на главной'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
