# Generated by Django 3.1.5 on 2021-02-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210219_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('living_address', models.CharField(max_length=500)),
                ('living_index', models.IntegerField()),
                ('registration_address', models.CharField(max_length=500)),
                ('registration_index', models.IntegerField()),
                ('passport_organization', models.CharField(max_length=500)),
                ('passport_date', models.DateField()),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
            ],
        ),
    ]
